include(FetchContent)

set(RESONANT_VST3_SDK_VERSION "3.8.0")
set(RESONANT_VST3_SDK_TAG "v3.8.0_build_66")
set(RESONANT_VST3_SDK_COMMIT "9fad9770f2ae8542ab1a548a68c1ad1ac690abe0")

set(SMTG_ENABLE_VST3_PLUGIN_EXAMPLES OFF CACHE BOOL "" FORCE)
set(SMTG_ENABLE_VST3_HOSTING_EXAMPLES OFF CACHE BOOL "" FORCE)
set(SMTG_ENABLE_VSTGUI_SUPPORT OFF CACHE BOOL "" FORCE)
set(SMTG_CREATE_PLUGIN_LINK OFF CACHE BOOL "" FORCE)
set(SMTG_RUN_VST_VALIDATOR OFF CACHE BOOL "" FORCE)

FetchContent_Declare(
    vst3sdk
    GIT_REPOSITORY https://github.com/steinbergmedia/vst3sdk.git
    GIT_TAG ${RESONANT_VST3_SDK_COMMIT}
    GIT_SHALLOW FALSE
    GIT_SUBMODULES_RECURSE TRUE
)

FetchContent_MakeAvailable(vst3sdk)
